#!/usr/bin/env python3
"""Regenerate the embedded icons from the vendored Lucide SVG sources."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
names = [
    'mouse-pointer-2', 'pencil', 'brush', 'slash',
    'rectangle-horizontal', 'rectangle-horizontal', 'circle', 'circle',
    'square-dashed', 'circle-dashed', 'stamp', 'image',
    'undo-2', 'redo-2', 'layers', 'sliders-horizontal', 'ellipsis',
    'plus', 'minus', 'arrow-up', 'arrow-down', 'highlighter',
    'arrow-up-right', 'corner-right-up', 'route', 'focus', 'circle',
    'list-ordered', 'eraser', 'circle',
    'eye', 'eye-off', 'lock', 'lock-open', 'chevron-down',
]
text = '// clang-format off\n// Generated by scripts/embed-lucide.py. Do not edit.\n'
text += '// Lucide: ISC / Feather MIT. See third-party/lucide/LICENSE.\n'
text += '#pragma once\n#include <array>\nnamespace program_draw {\n'
text += f'inline constexpr std::array<const char *, {len(names)}> LucideSvg = {{\n'
for name in names:
    svg = (root / 'third-party/lucide/icons' / f'{name}.svg').read_text().strip()
    text += f'    // {name}\n    R"lucide({svg})lucide",\n'
text += '};\n}\n// clang-format on\n'
(root / 'src/lucide-icons.hpp').write_text(text)
